spring:
  kafka:
    consumer:
      auto-offset-reset: latest
      max-poll-records: 10
      enable-auto-commit: false
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
axon:
  serializer:
    general:
      default
    events:
      jackson
    messages:
      default
  kafka:
    bootstrap-servers: localhost:9092
    client-id: shopping-service
    properties:
      security.protocol: PLAINTEXT
    publisher:
      confirmation-mode: transactional
    producer:
      transaction-id-prefix: kafka-shopping-events
      retries: 5
      event-processor-mode: subscribing
    fetcher:
      poll-timeout: 3000
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: tracking
---
spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=Postgres;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: test
---
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  config:
    activate:
      on-profile: local
  sql:
    init:
      platform: postgres