spring:
  kafka:
    consumer:
      auto-offset-reset: latest
      max-poll-records: 10
      enable-auto-commit: false
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    stream:
      bindings:
        input:
          group: shopping-service
          contentType: "application/vnd.cloudevent+json"
        onProductEvent-in-0:
          destination: democom.events.inventory.product
          consumer:
            concurrency: 8
---
spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=Postgres;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: test